import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Define the Staff interface
interface Staff {
  id: string | number;
  staff_name: string;
  staff_image: string;
  staff_contact: string;
}

// Initialize Supabase client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

export async function POST(request: NextRequest): Promise<NextResponse> {
  console.log('=== BACKEND POST STAFF DEBUG ===');
  
  // Check for authorization header
  const authHeader = request.headers.get('Authorization');
  console.log('Auth header present:', !!authHeader);
  console.log('Auth header preview:', authHeader ? authHeader.substring(0, 20) + '...' : 'null');
  
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    console.log('Auth header missing or malformed');
    return NextResponse.json(
      { message: 'Authorization token is missing or malformed.' },
      { status: 401 }
    );
  }
  const token = authHeader.substring(7);
  console.log('Extracted token preview:', token.substring(0, 20) + '...');

  try {
    // Verify the token with Supabase
    console.log('Verifying token with Supabase...');
    const { data: { user }, error: userError } = await supabase.auth.getUser(token);
    
    if (userError) {
      console.log('Supabase auth error:', userError);
      return NextResponse.json(
        { message: 'Invalid authentication token.' },
        { status: 403 }
      );
    }
    if (!user) {
      console.log('No user returned from Supabase');
      return NextResponse.json(
        { message: 'Invalid authentication token.' },
        { status: 403 }
      );
    }
    console.log('User authenticated:', user.id, user.email);

    // Parse the request body
    console.log('Parsing request body...');
    const body: Omit<Staff, 'id'> = await request.json(); // Omit 'id' as it's generated by DB
    
    console.log('Request body:', body);
    
    const { staff_name, staff_image, staff_contact } = body;

    console.log('Extracted fields:', { staff_name, staff_image, staff_contact });

    // Validate required fields
    if (!staff_name || staff_name.trim() === '') {
      console.log('Validation failed: staff_name is required.');
      return NextResponse.json(
        { message: 'staff_name is required.' },
        { status: 400 }
      );
    }

    // Prepare data for insertion
    console.log('Preparing data for insertion...');
    const insertData = {
      user_id: user.id,
      staff_name: staff_name.trim(),
      staff_image: staff_image?.trim() || null, // Use null for empty image URL
      staff_contact: staff_contact?.trim() || '', // Use empty string for empty contact
      created_at: new Date().toISOString(), // Supabase handles this automatically if column default is now()
    };
    
    console.log('Insert data:', insertData);

    // Insert the new staff member
    console.log('Inserting staff member into database...');
    const { data: newStaff, error: insertError } = await supabase
      .from('staff') // Changed from 'doctors' to 'staff'
      .insert(insertData)
      .select()
      .single();

    if (insertError) {
      console.error('Database insertion error:', insertError);
      console.error('Error details:', {
        code: insertError.code,
        message: insertError.message,
        details: insertError.details,
        hint: insertError.hint
      });
      return NextResponse.json(
        { 
          message: 'Failed to create staff member.',
          error: insertError.message,
          code: insertError.code
        },
        { status: 500 }
      );
    }

    console.log('Staff member created successfully:', newStaff);
    
    return NextResponse.json(
      {
        message: 'Staff member created successfully!',
        staff: newStaff
      },
      { status: 201 }
    );

  } catch (err: unknown) {
    console.error('Unexpected error creating staff member:', err);
    const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
    return NextResponse.json(
      { 
        message: 'An error occurred while creating the staff member.',
        error: errorMessage
      },
      { status: 500 }
    );
  }
}
