import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Define the Location interface to match your frontend component
interface Location {
  id: string | number;
  location_name: string;
  location_address: string;
  location_phone: string;
  location_header: string;
  location_footer: string;
  setting_toggle_location_address: boolean;
  setting_toggle_location_phone: boolean;
  setting_toggle_location_header: boolean;
  setting_toggle_location_doctor: boolean;
  setting_toggle_location_doctor_image: boolean;
  setting_toggle_location_doctor_bio: boolean;
  setting_toggle_staff: boolean;
  setting_location_toggle_staff_image: boolean;
  setting_location_toggle_staff_contact: boolean;
  setting_location_toggle_location_footer: boolean;
}

// Initialize Supabase client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

export async function POST(request: NextRequest): Promise<NextResponse> {
  console.log('=== BACKEND POST LOCATION DEBUG ===');
  
  // Check for authorization header
  const authHeader = request.headers.get('Authorization');
  console.log('Auth header present:', !!authHeader);
  console.log('Auth header preview:', authHeader ? authHeader.substring(0, 20) + '...' : 'null');
  
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    console.log('Auth header missing or malformed');
    return NextResponse.json(
      { message: 'Authorization token is missing or malformed.' },
      { status: 401 }
    );
  }
  const token = authHeader.substring(7);
  console.log('Extracted token preview:', token.substring(0, 20) + '...');

  try {
    // Verify the token with Supabase
    console.log('Verifying token with Supabase...');
    const { data: { user }, error: userError } = await supabase.auth.getUser(token);
    
    if (userError) {
      console.log('Supabase auth error:', userError);
      return NextResponse.json(
        { message: 'Invalid authentication token.' },
        { status: 403 }
      );
    }
    if (!user) {
      console.log('No user returned from Supabase');
      return NextResponse.json(
        { message: 'Invalid authentication token.' },
        { status: 403 }
      );
    }
    console.log('User authenticated:', user.id, user.email);

    // Parse the request body
    console.log('Parsing request body...');
    // For POST, we expect all fields to be provided, though some might be empty strings
    const body: Omit<Location, 'id'> = await request.json(); // Omit 'id' as it's generated by DB
    
    console.log('Request body:', body);
    
    const { 
      location_name, 
      location_address, 
      location_phone, 
      location_header, 
      location_footer,
      setting_toggle_location_address,
      setting_toggle_location_phone,
      setting_toggle_location_header,
      setting_toggle_location_doctor,
      setting_toggle_location_doctor_image,
      setting_toggle_location_doctor_bio,
      setting_toggle_staff,
      setting_location_toggle_staff_image,
      setting_location_toggle_staff_contact,
      setting_location_toggle_location_footer,
    } = body;

    console.log('Extracted fields:', { 
      location_name, 
      location_address, 
      location_phone, 
      location_header, 
      location_footer,
      setting_toggle_location_address,
      setting_toggle_location_phone,
      setting_toggle_location_header,
      setting_toggle_location_doctor,
      setting_toggle_location_doctor_image,
      setting_toggle_location_doctor_bio,
      setting_toggle_staff,
      setting_location_toggle_staff_image,
      setting_location_toggle_staff_contact,
      setting_location_toggle_location_footer,
    });

    // Validate required fields
    if (!location_name || location_name.trim() === '') {
      console.log('Validation failed: location_name is required.');
      return NextResponse.json(
        { message: 'location_name is required.' },
        { status: 400 }
      );
    }

    // Prepare data for insertion
    console.log('Preparing data for insertion...');
    const insertData = {
      user_id: user.id,
      location_name: location_name.trim(),
      location_address: location_address?.trim() || '', // Ensure default empty string for optional fields
      location_phone: location_phone?.trim() || '',
      location_header: location_header?.trim() || '',
      location_footer: location_footer?.trim() || '',
      setting_toggle_location_address: setting_toggle_location_address,
      setting_toggle_location_phone: setting_toggle_location_phone,
      setting_toggle_location_header: setting_toggle_location_header,
      setting_toggle_location_doctor: setting_toggle_location_doctor,
      setting_toggle_location_doctor_image: setting_toggle_location_doctor_image,
      setting_toggle_location_doctor_bio: setting_toggle_location_doctor_bio,
      setting_toggle_staff: setting_toggle_staff,
      setting_location_toggle_staff_image: setting_location_toggle_staff_image,
      setting_location_toggle_staff_contact: setting_location_toggle_staff_contact,
      setting_location_toggle_location_footer: setting_location_toggle_location_footer,
      created_at: new Date().toISOString(), // Supabase handles this automatically if column default is now()
    };
    
    console.log('Insert data:', insertData);

    // Insert the new location
    console.log('Inserting location into database...');
    const { data: newLocation, error: insertError } = await supabase
      .from('locations') // Changed from 'doctors' to 'locations'
      .insert(insertData)
      .select()
      .single();

    if (insertError) {
      console.error('Database insertion error:', insertError);
      console.error('Error details:', {
        code: insertError.code,
        message: insertError.message,
        details: insertError.details,
        hint: insertError.hint
      });
      return NextResponse.json(
        { 
          message: 'Failed to create location.',
          error: insertError.message,
          code: insertError.code
        },
        { status: 500 }
      );
    }

    console.log('Location created successfully:', newLocation);
    
    return NextResponse.json(
      {
        message: 'Location created successfully!',
        location: newLocation
      },
      { status: 201 }
    );

  } catch (err: unknown) {
    console.error('Unexpected error creating location:', err);
    const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
    return NextResponse.json(
      { 
        message: 'An error occurred while creating the location.',
        error: errorMessage
      },
      { status: 500 }
    );
  }
}
